# Project information
site_name: Airlink by EnAccess
site_url: https://airlinkdocs.enaccess.org/
site_description: >-
  This is the documentation for the Airlink by EnAccess

# Repository
repo_name: EnAccess/Airlink-docs
repo_url: https://github.com/EnAccess/Airlink-docs
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # schema: enaccess
    primary: custom
    accent: custom
  logo: assets/EnAccess_Logo_Digital_Inverse.svg
  features:
    - content.action.edit
    - content.action.view
    # Disabled to prevent automatic inlining
    # - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # I find this has a weird look and feel, but can be enabled.
    # - toc.integrate

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EnAccess
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/enaccessfdn
  analytics:
    provider: google
    property: G-PTQ3NKJGK5
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EnAccess
      repo: OpenSmartMeter
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde

# Extra stuff
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Use Cases:
      - Use Case - Manufacturer: Use Cases/Use Case - Device Manufacturer.md
      - Use Case - NGO: Use Cases/Use Case - NGO.md
      - Use Case - PAYGO: Use Cases/Use Case - Paygo Entrepreneur.md
  - AirLink App:
      - Home: AirLink App.md
  - AirLink Devices:
      - Home: AirLink Devices.md
      - Range Testing Results: AirLink Devices/Range Testing Results.md
  - AirLink Server:
      - Home: AirLink Server.md
  - Quick-start guide: Quick-start guide.md
  - Connecting to Solaris or Angaza: Connecting to Solaris or Angaza.md
