name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        globs: |
          docs/**/*.md
